version: "3.8"
services:
  pyatlas-main:
    image: iamprithaj/pyatlas
    container_name: dev-pyatlas-main
    restart: always
    build:
      context: .
      dockerfile: dev.Dockerfile

    environment:
      - ENV=development
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_HOST=$POSTGRES_HOST
      - POSTGRES_PORT=$POSTGRES_PORT
    volumes:
      - .:/usr/bin/pyatlas/

  pyatlas-db:
    image: postgres:13 
    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    container_name: dev-pyatlas-db
    restart: always
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust